# Site settings
title: BINGO's Blog
SEOTitle: BINGO's Blog
header-img: img/post-bg-desk.jpg
email: yanhuibin315@163.com
description: "Every failure is leading towards success."
keyword: "机器学习, 区块链, 自然语言处理, 运动, 个人博客"
url: "http://yanhuibin315.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/yanhuibin315/yanhuibin315.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "你见过凌晨四点的北京么？加班时候见过..."
sidebar-avatar: /img/about-BY-gentle.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     u/2243872910
zhihu_username:     bingoyan-32
github_username:    yanhuibin315
twitter_username:   yan_bingo




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: 

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID:                             #生成的clientID
  clientSecret:     #生成的clientSecret
  repo:     #仓库名称
  owner:     #github用户名
  admin: 
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "王威廉[NLP]",
        href: "https://sites.cs.ucsb.edu/~william/"
    },{
        title: "吴恩达[ML]",
        href: "https://www.andrewng.org/"
    },{
        title: "哈希学习[DM]",
        href: "http://cs.nju.edu.cn/lwj/L2H.html"
    },{
        title: "伯荧[Blog]",
        href: "https://qiubaiying.github.io/"
    },{
        title: "袁勇[CV]",
        href: "http://yongyuan.name/"
    },{
        title: "OPENKG知识图谱社区[KG]",
        href: "http://blog.openkg.cn/"
    },{
        title: "刘焕勇[KG]",
        href: "https://liuhuanyong.github.io/"
    },{
        title: "Ramesh Nc[CV]",
        href: "https://www.informatalks.com/"
    },{
        title: "Createmomo[ML]",
        href: "https://createmomo.github.io/"
    },{
        title: "陈丹琦[NLP]",
        href: "https://www.cs.princeton.edu/~danqic/"
    },{
        title: "扬帆起航",
        href: "http://note4lin.top/"
    },{
        title: "阮一峰的网络日志",
        href: "http://www.ruanyifeng.com/blog/"
    },{
        title: "刘知远-知乎[KG]",
        href: "https://www.zhihu.com/people/zibuyu9/activities"
    },{
        title: "宋井宽[GAN]",
        href: "http://cfm.uestc.edu.cn/~songjingkuan/"
    },{
        title: "Shikhar Vashishth[KG]",
        href: "https://shikhar-vashishth.github.io/"
    },{
        title: "DANLU CHEN[ML]",
        href: "http://taineleau.me/"
    },{
        title: "Michael Schlichtkrull",
        href: "http://michschli.github.io/"
    },{
        title: "Jay Alammar",
        href: "http://jalammar.github.io/"
    },{
        title: "Fen Jie",
        href: "https://vonfeng.github.io/"
    }
]
